#!/usr/bin/env python
"""Endpoint geometry of the PROMPTED cross-model persona corpus (companion to oct_geometry.py).

Same method as the OCT LoRA analysis (SBERT endpoints, set-to-set distances, two-labeling
silhouette, variance decomposition — arxiv 2606.30571 adapted) applied to the persona-PROMPT
sweep: 12 traits × {rich, grounded} generated system prompts + `base` control, on five models
(llama-3.1-8b local + gpt-4.1 / kimi-k2 / llama-3.3-70b / deepseek-v4-pro via OpenRouter),
temp 0.7. 125 conditions; llama-8b has 13-15 runs/condition, the API models 5.

Questions:
 1. same prompt across models — how similar? (analog of the OCT cross-base question)
 2. same model across prompts — how different?
 3. rich vs grounded variant of the SAME trait — same basin?

    ./.venv/bin/python prompt_geometry.py
"""

import argparse
import glob
import json
import os

import numpy as np

from oct_geometry import d_set_sq
from oct_dynamics import sil

TRAITS = ("honesty sincerity goodness humor impulsiveness loving mathematical nonchalance "
          "poeticism remorse sarcasm sycophancy").split()
PERSONAS = ["base"] + [f"{t}_{k}" for t in TRAITS for k in ("rich", "grounded")]
# Two selectable model sets (--models).
#   prompt5  the original cross-model prompt sweep. Keeps every published figure/number
#            reproducible, but it is NOT comparable cell-for-cell with oct_geometry.py: that
#            corpus is {llama-3.1-8b, qwen-2.5-7b, gemma-3-4b} and this one overlaps it in
#            llama-8b alone, so a LoRA-vs-prompt contrast drawn across the two also swaps a
#            small-open-weights trio for a mostly-large-API set.
#   matched  exactly the three OCT LoRA bases, so "fine-tuning transfers the voice, prompting
#            transfers the theme" can be tested with the model set HELD FIXED. Generated by
#            run_persona_oct_bases_on_pod.sh; the base control is the OCT sweep's own
#            results/base_ai2ai_<slug> (identical condition, deliberately not regenerated).
MODEL_SETS = {
    "prompt5": {"llama-8b": "", "gpt-4.1": "_gpt-4.1", "kimi-k2": "_kimi-k2",
                "llama-3.3-70b": "_llama-3.3-70b", "deepseek-v4-pro": "_deepseek-v4-pro"},
    "matched": {"llama-8b": "", "qwen-2.5-7b": "_qwen-2.5-7b", "gemma-3-4b": "_gemma-3-4b"},
}
MODELS = MODEL_SETS["prompt5"]        # rebound by main() per --models
MODEL_SET = "prompt5"
ENDPOINT_TURNS = 6
N_TURNS = 30
OUT_DIR = "results/prompt_geometry"
# Cache is per model set — sharing one file across sets would silently reuse the wrong
# embeddings (the length check alone cannot tell two different corpora apart).
CACHE = os.path.join(OUT_DIR, "embeddings_temp0.7.npz")


def _select_model_set(name):
    """Rebind the module globals that depend on which model set is active."""
    global MODELS, MODEL_SET, OUT_DIR, CACHE
    MODEL_SET = name
    MODELS = MODEL_SETS[name]
    OUT_DIR = "results/prompt_geometry" if name == "prompt5" else f"results/prompt_geometry_{name}"
    CACHE = os.path.join(OUT_DIR, "embeddings_temp0.7.npz")


def cond_dir(p, m):
    s = MODELS[m]
    if p == "base":
        return f"results/base_ai2ai{s}"
    t, kind = p.rsplit("_", 1)
    return f"results/{t}_{kind}prompt_ai2ai{s}"


def load_turns():
    rows = []
    for p in PERSONAS:
        for m in MODELS:
            fs = glob.glob(f"{cond_dir(p, m)}/two_instance*temp0.7.json")
            if not fs:
                print(f"!! missing condition: {p}/{m}")
                continue
            for run in json.load(open(fs[0]))["runs"]:
                for i, t in enumerate(run["turns"]):
                    text = (t.get("content_clean") or t.get("content") or "").strip()
                    if text:
                        rows.append((p, m, run["run_index"], i, text))
    return rows


def embed(rows):
    if os.path.exists(CACHE):
        z = np.load(CACHE)
        if len(z["emb"]) == len(rows):
            return z["emb"]
    import torch
    from sentence_transformers import SentenceTransformer
    device = "mps" if torch.backends.mps.is_available() else None
    model = SentenceTransformer("all-MiniLM-L6-v2", device=device)
    emb = model.encode([r[4] for r in rows], batch_size=128, show_progress_bar=True,
                       normalize_embeddings=True)
    os.makedirs(OUT_DIR, exist_ok=True)
    np.savez_compressed(CACHE, emb=emb)
    return emb


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--models", choices=sorted(MODEL_SETS), default="prompt5",
                    help="prompt5 = original 5-model sweep (default, reproduces published figures); "
                         "matched = the three OCT LoRA bases, for a model-set-controlled "
                         "LoRA-vs-prompt contrast")
    args = ap.parse_args()
    _select_model_set(args.models)
    print(f"model set: {args.models} -> {list(MODELS)}")
    rows = load_turns()
    emb = embed(rows)
    runs = {}
    for (p, m, ri, ti, _), e in zip(rows, emb):
        runs.setdefault((p, m, ri), {})[ti] = e
    E, labels = [], []
    for key, turns in sorted(runs.items()):
        tis = sorted(turns)
        E.append(np.mean([turns[t] for t in tis[-ENDPOINT_TURNS:]], axis=0))
        labels.append(key[:2])
    E = np.array(E)
    personas = np.array([l[0] for l in labels])
    models = np.array([l[1] for l in labels])
    conds = [(p, m) for p in PERSONAS for m in MODELS]
    idx = {c: np.where((personas == c[0]) & (models == c[1]))[0] for c in conds}
    conds = [c for c in conds if len(idx[c]) >= 4]
    print(f"{len(rows)} turns, {len(E)} endpoints, {len(conds)} conditions")

    n = len(conds)
    D = np.zeros((n, n))
    for i in range(n):
        for j in range(i + 1, n):
            D[i, j] = D[j, i] = d_set_sq(E[idx[conds[i]]], E[idx[conds[j]]])

    def trait(p):
        return None if p == "base" else p.rsplit("_", 1)[0]

    def bm(pred):
        vals = [D[i, j] for i in range(n) for j in range(i + 1, n) if pred(conds[i], conds[j])]
        return float(np.mean(vals)), len(vals)

    same_p_xm, _ = bm(lambda a, b: a[0] == b[0] != "base" and a[1] != b[1])
    base_xm, _ = bm(lambda a, b: a[0] == b[0] == "base" and a[1] != b[1])
    same_m_xp, _ = bm(lambda a, b: a[0] != b[0] and a[1] == b[1])
    xx, _ = bm(lambda a, b: a[0] != b[0] and a[1] != b[1])
    # rich vs grounded of the SAME trait, same model
    kin_same_m, _ = bm(lambda a, b: a[0] != b[0] and a[1] == b[1]
                       and trait(a[0]) is not None and trait(a[0]) == trait(b[0]))
    # different trait entirely, same model (excluding base and same-trait pairs)
    difftrait_same_m, _ = bm(lambda a, b: a[1] == b[1] and trait(a[0]) is not None
                             and trait(b[0]) is not None and trait(a[0]) != trait(b[0]))

    sil_p, p_p = sil(E, personas, perms=1000)
    sil_m, p_m = sil(E, models, perms=1000)
    sil_t, p_t = sil(E[personas != "base"],
                     [trait(p) for p in personas[personas != "base"]], perms=1000)

    # balanced variance decomposition: subsample every condition to 5 runs
    rng = np.random.default_rng(0)
    sub = np.concatenate([rng.choice(idx[c], 5, replace=False) for c in conds])
    Es, ps, ms = E[sub], personas[sub], models[sub]
    mu = Es.mean(0)
    ss_tot = ((Es - mu) ** 2).sum()
    ss_p = sum(((Es[ps == p].mean(0) - mu) ** 2).sum() * (ps == p).sum() for p in PERSONAS)
    ss_m = sum(((Es[ms == m].mean(0) - mu) ** 2).sum() * (ms == m).sum() for m in MODELS)
    ss_i = sum(((Es[(ps == p) & (ms == m)].mean(0) - Es[ps == p].mean(0)
                 - Es[ms == m].mean(0) + mu) ** 2).sum() * ((ps == p) & (ms == m)).sum()
               for p, m in conds)
    ss_r = ss_tot - ss_p - ss_m - ss_i

    nn_same = sum(1 for i in range(n)
                  if conds[min((j for j in range(n) if j != i), key=lambda j: D[i, j])][0]
                  == conds[i][0])
    nn_same_trait = sum(1 for i in range(n) if trait(conds[i][0]) is not None and
                        trait(conds[min((j for j in range(n) if j != i),
                                        key=lambda j: D[i, j])][0]) == trait(conds[i][0]))

    per_persona = {p: np.mean([D[conds.index((p, m1))][conds.index((p, m2))]
                               for a, m1 in enumerate(MODELS) for m2 in list(MODELS)[a + 1:]
                               if (p, m1) in conds and (p, m2) in conds])
                   for p in PERSONAS}

    L = ["# Prompted cross-model endpoint geometry (temp 0.7)\n",
         f"{len(E)} run endpoints, {n} conditions ({len(PERSONAS)} personas x {len(MODELS)} "
         f"models: {', '.join(MODELS)}). Same method as the OCT LoRA analysis.\n",
         ("Model set `prompt5`: API models have only 5 runs/condition, so set statistics are "
          "noisier than the LoRA corpus, and this set overlaps oct_geometry.py in llama-8b "
          "ALONE — do not read a LoRA-vs-prompt contrast off it without noting the model-set "
          "swap. Use `--models matched` for the controlled comparison.\n"
          if MODEL_SET == "prompt5" else
          "Model set `matched`: the same three bases as oct_geometry.py at the same 15 runs x 30 "
          "turns, so LoRA-vs-prompt here is measured with the model set held fixed.\n"),
         "## Headline block means (lower = more similar)\n",
         f"- same prompt, different model:        **{same_p_xm:.3f}**",
         f"- rich vs grounded same trait, same model: **{kin_same_m:.3f}**",
         f"- different trait, same model:         **{difftrait_same_m:.3f}**",
         f"- same model, different persona (all): **{same_m_xp:.3f}**",
         f"- different persona and model:         **{xx:.3f}**",
         f"- `base` control, different model:     **{base_xm:.3f}**\n",
         "## Silhouettes (perm. test, 1000 shuffles)\n",
         f"- by PERSONA (25 labels): **{sil_p:.4f}** (p={p_p:.3f})",
         f"- by TRAIT (12 labels, rich+grounded pooled, base excluded): **{sil_t:.4f}** (p={p_t:.3f})",
         f"- by MODEL (5 labels):   **{sil_m:.4f}** (p={p_m:.3f})\n",
         "## Variance decomposition (balanced 5-run subsample)\n",
         f"- persona: **{100 * ss_p / ss_tot:.1f}%**",
         f"- model: **{100 * ss_m / ss_tot:.1f}%**",
         f"- persona x model: **{100 * ss_i / ss_tot:.1f}%**",
         f"- seed residual: **{100 * ss_r / ss_tot:.1f}%**\n",
         f"## Nearest neighbor: same persona {nn_same}/{n}; same trait "
         f"{nn_same_trait}/{n - len(MODELS)} (of non-base)\n",
         "## Per-persona mean cross-model distance (sorted)\n"]
    for p, v in sorted(per_persona.items(), key=lambda kv: kv[1]):
        L.append(f"- {p}: {v:.3f}")
    out = "\n".join(L)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(f"{OUT_DIR}/report.md", "w") as f:
        f.write(out + "\n")
    print(out)

    # heatmap, persona-major (5-model blocks); persona labels at block centers
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(13, 11.5))
    im = ax.imshow(D, cmap="Blues_r", interpolation="nearest")
    nm = len(MODELS)
    centers = [i * nm + nm / 2 - 0.5 for i in range(len(PERSONAS))]
    ax.set_xticks(centers, PERSONAS, rotation=90, fontsize=6.5)
    ax.set_yticks(centers, PERSONAS, fontsize=6.5)
    for k in range(nm, n, nm):
        ax.axhline(k - 0.5, color="white", lw=1.2)
        ax.axvline(k - 0.5, color="white", lw=1.2)
    ax.set_title(f"Prompted corpus [{MODEL_SET}]: endpoint set-to-set distance (dark = similar) — "
                 f"persona-major, {len(MODELS)} models per block", fontsize=10)
    for spine in ax.spines.values():
        spine.set_visible(False)
    cb = fig.colorbar(im, ax=ax, shrink=0.7)
    cb.set_label("d_set", fontsize=8)
    fig.tight_layout()
    fig.savefig(f"{OUT_DIR}/distance_heatmap.png", dpi=160)
    print(f"\nwrote {OUT_DIR}/report.md + distance_heatmap.png")


if __name__ == "__main__":
    main()
